# Generated by Django 5.1.3 on 2024-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_register',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
