# Generated by Django 5.1.3 on 2024-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
